% SPDX-License-Identifier: GPL-3.0-or-later
% EyeSort - Region-aware eye-tracking event labeling for EEGLAB
% Copyright (C) 2025 Eye Movements & Cognition Lab (USF)
% Copyright (C) 2025 Brandon Snyder, Sara Milligan, Elizabeth Schotter
%
% This program is free software: you can redistribute it and/or modify
% it under the terms of the GNU General Public License as published by
% the Free Software Foundation, either version 3 of the License, or
% (at your option) any later version.
%
% This program is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
% GNU General Public License for more details.
%
% You should have received a copy of the GNU General Public License
% along with this program.  If not, see <https://www.gnu.org/licenses/>.

% Author: Brandon Snyder

function helpText = get_input_help(fieldName)
    % GET_INPUT_HELP - Returns detailed help text for GUI input fields
    
    helpDB = struct();
    
    % Define help text for each field
    helpDB.rtl = ['Right-to-Left Reading Language:\n\n' ...
        'Check this box if your stimulus text is written in a right-to-left language ' ...
        '(e.g., Hebrew, Arabic, Farsi).\n\n' ...
        'When enabled, interest area boundaries are computed from right to left, ' ...
        'so that region positions correctly reflect the reading direction of the text.\n\n' ...
        'Leave unchecked for standard left-to-right languages (e.g., English, German).'];
    
    helpDB.offset = ['Sentence Offset in Pixels:\n\n' ...
        'The horizontal pixel offset from the start of the display to where ' ...
        'the sentence text begins. This value adjusts for any margin or ' ...
        'padding in your stimulus presentation.\n\n' ...
        'Example: 281\n\n' ...
        'Range: Typically 0-500 pixels depending on your display setup.'];
    
    helpDB.pxPerChar = ['Pixels-Per-Character:\n\n' ...
        'The width in pixels of each character in your stimulus text. ' ...
        'This is used to calculate character positions for interest area boundaries.\n\n' ...
        'Example: 14\n' ...
        'Note: Measure this from your actual stimulus font and size.'];
    
    helpDB.numRegions = ['Number of Interest Regions:\n\n' ...
        'The total number of interest areas to define for each sentence. ' ...
        'Each region will be analyzed separately for fixation patterns.\n\n' ...
        'Example: 4\n' ...
        'Range: 1-20 regions (practical limit)'];
    
    helpDB.regionNames = ['Region Names:\n\n' ...
        'Comma-separated list of names for each interest area. ' ...
        'Must match the number specified in "Number of Interest Regions".\n\n' ...
        'Example: Beginning, PreTarget, Target_word, Ending\n' ...
        'Format: Use descriptive names without spaces (use underscores instead)'];
    
    helpDB.condType = ['Condition Label Column Name(s):\n\n' ...
        'The column names in your text file that contains the condition ' ...
        'labels (descriptive names for experimental conditions). Can have multiple columns.\n\n' ...
        'Example: condition_one, condition_two'];
    
    helpDB.condName = ['Condition Trigger Code Column Name:\n\n' ...
        'The column name containing numeric trigger codes that correspond ' ...
        'to each experimental condition in your EEG data.\n\n' ...
        'Example: trigcondition\n' ...
        'Hint: Column contains values like 211, 213, 221, 223'];
    
    helpDB.itemName = ['Item Trigger Code Column Name:\n\n' ...
        'The column name containing trigger codes that identify specific ' ...
        'stimulus items or trials in your EEG data.\n\n' ...
        'Example: trigitem\n' ...
        'Hint: Column contains values like S1, S2, S3, etc.'];
    
    helpDB.startCode = ['Start Trial Code:\n\n' ...
        'The trigger code that marks the beginning of each trial in your ' ...
        'EEG data. Used to align behavioral and EEG data.\n\n' ...
        'Example: S254\n' ...
        'Format: Use the exact trigger format from your EEG system'];
    
    helpDB.endCode = ['End Trial Code:\n\n' ...
        'The trigger code that marks the end of each trial in your ' ...
        'EEG data.\n\n' ...
        'Example: S255\n' ...
        'Format: Use the exact trigger format from your EEG system'];
    
    helpDB.sentenceStart = ['Stimulus Start Code:\n\n' ...
        'The optional trigger code marking when the specific stimulus time window begins ' ...
        'within each trial. Only used when "Eye-Event Time Window" is checked.\n\n' ...
        'Example: S250\n' ...
        'Usage: Allows precise timing of interest area analysis'];
    
    helpDB.sentenceEnd = ['Stimulus End Code:\n\n' ...
        'The trigger code marking when the specific stimulus time window ends ' ...
        'within each trial. Only used when "Specific Stimulus Period" is checked.\n\n' ...
        'Example: S251\n' ...
        'Usage: Defines the window for eye-tracking analysis'];
    
    helpDB.condTriggers = ['Condition Triggers:\n\n' ...
        'Comma-separated list of trigger codes that identify different ' ...
        'experimental conditions in your EEG data.\n\n' ...
        'Example: S211, S213, S221, S223\n' ...
        'Format: Match the exact trigger codes from your experiment'];
    
    helpDB.itemTriggers = ['Item Triggers:\n\n' ...
        'Trigger codes identifying individual stimulus items. Supports ' ...
        'range notation for efficient specification.\n\n' ...
        'Default: S1:S112\n' ...
        'Examples: "S1:S50" or "S1:S50, S60:S80"\n' ...
        'Format: Use ranges (S1:S112) or individual codes (S1, S2, S3)'];
    
    helpDB.fixationType = ['Fixation Event Name:\n\n' ...
        'The name used in your eye-tracking data to identify fixation events.\n\n' ...
        'Default: R_fixation\n' ...
        'Note: Must match the exact event type name in your EEG dataset'];
    
    helpDB.fixationXField = ['Fixation X Position Field:\n\n' ...
        'The field name containing the horizontal position data for fixations.\n\n' ...
        'Default: fix_avgpos_x\n' ...
        'Usage: Used to determine which interest area contains each fixation'];
    
    helpDB.saccadeType = ['Saccade Event Name:\n\n' ...
        'The name used in your eye-tracking data to identify saccade events.\n\n' ...
        'Default: R_saccade\n' ...
        'Note: Must match the exact event type name in your EEG dataset'];
    
    helpDB.saccadeStartXField = ['Saccade Start X Position Field:\n\n' ...
        'The field name containing the horizontal start position of saccades.\n\n' ...
        'Default: sac_startpos_x\n' ...
        'Usage: Used to determine saccade origin for transition analysis'];
    
    helpDB.saccadeEndXField = ['Saccade End X Position Field:\n\n' ...
        'The field name containing the horizontal end position of saccades.\n\n' ...
        'Default: sac_endpos_x\n' ...
        'Usage: Used to determine saccade destination for transition analysis'];
    
    % Return help text for requested field
    if isfield(helpDB, fieldName)
        helpText = helpDB.(fieldName);
    else
        helpText = ['Help text not available for field: ' fieldName];
    end
end