% SPDX-License-Identifier: GPL-3.0-or-later
% EyeSort - Region-aware eye-tracking event labeling for EEGLAB
% Copyright (C) 2025 Eye Movements & Cognition Lab (USF)
% Copyright (C) 2025 Brandon Snyder, Sara Milligan, Elizabeth Schotter

% Author: Brandon Snyder

function diagnostics = import_column_diagnostics(importDiagnostics, condColName, itemColName)
%IMPORT_COLUMN_DIAGNOSTICS Build diagnostic struct from IA column import data.
%
% INPUTS:
%   importDiagnostics - EEG.eyesort_import_diagnostics struct (produced by
%                       import_ia_columns)
%   condColName       - Condition column name used in field-name labels
%   itemColName       - Item column name used in field-name labels
%
% OUTPUT:
%   diagnostics - Struct array in EyeSort diagnostic format (severity, inputName,
%                 fieldName, userValue, message, suggestion).  Empty when there
%                 are no import problems.

    diagnostics = struct('severity', {}, 'inputName', {}, 'fieldName', {}, ...
        'userValue', {}, 'message', {}, 'suggestion', {});

    colField      = sprintf('%s x %s', condColName, itemColName);
    validEventKeys = importDiagnostics.valid_event_keys;
    assignedEvents = importDiagnostics.assigned_events;
    missingKeys    = importDiagnostics.missing_keys;
    unusedTextKeys = importDiagnostics.unused_text_keys;

    if validEventKeys == 0
        diagnostics(end+1) = struct( ...
            'severity', 'error', ...
            'inputName', 'IA column import', ...
            'fieldName', 'condition_number / item_number', ...
            'userValue', '', ...
            'message', 'No EEG events had valid condition_number and item_number values to match against the IA file.', ...
            'suggestion', 'Run Step 2 successfully first and check trigger diagnostics if condition/item values are all zero.'); %#ok<AGROW>
    elseif assignedEvents == 0
        shownFileKeys = unusedTextKeys(1:min(10, length(unusedTextKeys)));
        diagnostics(end+1) = struct( ...
            'severity', 'error', ...
            'inputName', 'IA column import', ...
            'fieldName', colField, ...
            'userValue', strjoin(shownFileKeys, ', '), ...
            'message', 'No EEG event condition/item keys matched rows in the IA file, so no columns were imported.', ...
            'suggestion', 'Check that the IA file condition/item columns use the same numeric values produced by Step 2 trigger matching.'); %#ok<AGROW>
    elseif ~isempty(missingKeys)
        shownMissing = missingKeys(1:min(10, length(missingKeys)));
        diagnostics(end+1) = struct( ...
            'severity', 'warning', ...
            'inputName', 'IA column import', ...
            'fieldName', colField, ...
            'userValue', strjoin(shownMissing, ', '), ...
            'message', sprintf('%d EEG condition/item key(s) were not found in the IA file and were skipped.', ...
                length(missingKeys)), ...
            'suggestion', 'Check whether the IA file is missing stimuli or whether trigger-derived condition/item values are incorrect.'); %#ok<AGROW>
    end
end
