% SPDX-License-Identifier: GPL-3.0-or-later
% EyeSort - Region-aware eye-tracking event labeling for EEGLAB
% Copyright (C) 2025 Eye Movements & Cognition Lab (USF)
% Copyright (C) 2025 Brandon Snyder, Sara Milligan, Elizabeth Schotter

function diagnostics = interest_area_assignment_diagnostics(step2Diagnostics, ...
        conditionColName, itemColName, conditionTriggerStr, itemTriggerStr)
%INTEREST_AREA_ASSIGNMENT_DIAGNOSTICS Build diagnostic struct from Step 2 assignment data.
%
% INPUTS:
%   step2Diagnostics    - EEG.eyesort_step2_diagnostics struct (produced by
%                         compute_text_based_ia / process_single_dataset)
%   conditionColName    - Condition column name used to label field names in warnings
%   itemColName         - Item column name used to label field names in warnings
%   conditionTriggerStr - (optional) Condition trigger string for error userValue
%   itemTriggerStr      - (optional) Item trigger string for error userValue
%
% OUTPUT:
%   diagnostics - Struct array in EyeSort diagnostic format (severity, inputName,
%                 fieldName, userValue, message, suggestion).  Empty when there
%                 are no assignment problems.

    if nargin < 4, conditionTriggerStr = ''; end
    if nargin < 5, itemTriggerStr = ''; end

    diagnostics = struct('severity', {}, 'inputName', {}, 'fieldName', {}, ...
        'userValue', {}, 'message', {}, 'suggestion', {});

    numAssigned         = step2Diagnostics.assigned_boundary_events;
    fixationsInRegion   = step2Diagnostics.fixations_assigned_to_region;
    fixationsSeen       = step2Diagnostics.fixation_events_seen;
    saccadesSeen        = step2Diagnostics.saccade_events_seen;
    missingTextKeys     = step2Diagnostics.missing_text_file_keys;
    unusedTextKeys      = step2Diagnostics.unused_text_file_keys;
    colField            = sprintf('%s x %s', conditionColName, itemColName);

    if numAssigned == 0
        likelyCauses = {};
        if step2Diagnostics.trial_start_matches == 0 || step2Diagnostics.trial_end_matches == 0
            likelyCauses{end+1} = 'trial start/end codes did not identify any complete trial windows'; %#ok<AGROW>
        end
        if step2Diagnostics.condition_trigger_matches == 0 || step2Diagnostics.item_trigger_matches == 0
            likelyCauses{end+1} = 'condition or item triggers did not match events inside trials'; %#ok<AGROW>
        end
        if step2Diagnostics.complete_key_events == 0
            likelyCauses{end+1} = 'no complete condition/item keys were created from EEG events'; %#ok<AGROW>
        end
        if step2Diagnostics.events_missing_text_key > 0
            likelyCauses{end+1} = 'EEG condition/item keys did not overlap with the interest-area text file'; %#ok<AGROW>
        end
        if step2Diagnostics.fixation_events_seen == 0 && step2Diagnostics.saccade_events_seen == 0
            likelyCauses{end+1} = 'the fixation/saccade event type inputs did not match any EEG events'; %#ok<AGROW>
        end
        if step2Diagnostics.missing_x_field_events > 0 || step2Diagnostics.invalid_x_position_events > 0
            likelyCauses{end+1} = 'fixation x-position field values were missing or invalid'; %#ok<AGROW>
        end
        if isempty(likelyCauses)
            likelyCauses = {'the EEG events and interest-area file did not produce assignable trials'};
        end
        trigUserValue = '';
        if ~isempty(conditionTriggerStr) || ~isempty(itemTriggerStr)
            trigUserValue = sprintf('Condition triggers: %s; Item triggers: %s', ...
                conditionTriggerStr, itemTriggerStr);
        end
        diagnostics(end+1) = struct( ...
            'severity', 'error', ...
            'inputName', 'Step 2 interest-area assignment', ...
            'fieldName', 'condition/item triggers and IA file rows', ...
            'userValue', trigUserValue, ...
            'message', sprintf(['No EEG events received interest-area boundaries. ' ...
                'Counts: starts=%d, ends=%d, condition matches=%d, item matches=%d, ' ...
                'complete keys=%d, missing IA keys=%d.'], ...
                step2Diagnostics.trial_start_matches, step2Diagnostics.trial_end_matches, ...
                step2Diagnostics.condition_trigger_matches, step2Diagnostics.item_trigger_matches, ...
                step2Diagnostics.complete_key_events, step2Diagnostics.events_missing_text_key), ...
            'suggestion', sprintf('Likely cause(s): %s. Check trigger inputs, event field names, and condition/item values in the IA text file.', ...
                strjoin(likelyCauses, '; '))); %#ok<AGROW>
    elseif numAssigned > 0 && fixationsSeen == 0 && saccadesSeen > 0
        diagnostics(end+1) = struct( ...
            'severity', 'warning', ...
            'inputName', 'Fixation event type', ...
            'fieldName', 'Fixation Event Type field', ...
            'userValue', sprintf('fixationsSeen=0, saccadesSeen=%d, assigned=%d', saccadesSeen, numAssigned), ...
            'message', sprintf(['No fixation events were matched by the Fixation Event Type string, ' ...
                'but %d saccade event(s) were matched. ' ...
                'All trial-level behaviour columns (current_region, pass index, etc.) will be empty.'], saccadesSeen), ...
            'suggestion', 'Check the Fixation Event Type field — the string must match the prefix used in your EEG data (e.g. "R_fixation", not "R_Fixation").'); %#ok<AGROW>
    elseif fixationsSeen > 0 && fixationsInRegion == 0
        diagnostics(end+1) = struct( ...
            'severity', 'warning', ...
            'inputName', 'Fixation-to-region assignment', ...
            'fieldName', 'offset / pxPerChar / region boundaries', ...
            'userValue', sprintf('%d fixation(s) seen, 0 landed inside a region boundary', fixationsSeen), ...
            'message', sprintf(['%d fixation event(s) had valid condition/item keys and a readable x-position, ' ...
                'but none fell within any computed region boundary. ' ...
                'All trial-level behaviour columns (current_region, pass index, etc.) will be empty.'], fixationsSeen), ...
            'suggestion', 'Check the Sentence Offset in Pixels and Pixels Per Character values. If either is wrong the region windows will be shifted or scaled away from all fixation positions.'); %#ok<AGROW>
    elseif ~isempty(missingTextKeys)
        shownKeys = missingTextKeys(1:min(10, length(missingTextKeys)));
        diagnostics(end+1) = struct( ...
            'severity', 'warning', ...
            'inputName', 'Interest-area text file rows', ...
            'fieldName', colField, ...
            'userValue', strjoin(shownKeys, ', '), ...
            'message', sprintf('%d EEG condition/item key(s) did not exist in the interest-area text file, so affected events were skipped.', ...
                length(missingTextKeys)), ...
            'suggestion', 'Check that the EEG condition/item trigger values overlap the condition and item columns in the IA text file.'); %#ok<AGROW>
    end

    if ~isempty(unusedTextKeys)
        shownUnused = unusedTextKeys(1:min(10, length(unusedTextKeys)));
        diagnostics(end+1) = struct( ...
            'severity', 'warning', ...
            'inputName', 'Unused interest-area text rows', ...
            'fieldName', colField, ...
            'userValue', strjoin(shownUnused, ', '), ...
            'message', sprintf('%d IA text-file key(s) were not observed in the EEG dataset.', ...
                length(unusedTextKeys)), ...
            'suggestion', 'This is safe if the text file intentionally contains extra stimuli; otherwise check condition/item coding.'); %#ok<AGROW>
    end
end
