% SPDX-License-Identifier: GPL-3.0-or-later
% EyeSort - Region-aware eye-tracking event labeling for EEGLAB
% Copyright (C) 2025 Eye Movements & Cognition Lab (USF)
% Copyright (C) 2025 Brandon Snyder, Sara Milligan, Elizabeth Schotter

% Author: Brandon Snyder

function show_field_help(fieldName)
    % SHOW_FIELD_HELP - Display help popup for specific input field
    
    % Get help text for the field
    helpText = get_input_help(fieldName);
    
    % Convert \n to actual line breaks for MATLAB display
    helpText = strrep(helpText, '\n', char(10));
    
    % Create help popup window
    hFig = figure('Name', ['Help: ' strrep(fieldName, '_', ' ')], ...
           'NumberTitle', 'off', ...
           'MenuBar', 'none', ...
           'ToolBar', 'none', ...
           'Position', [400, 400, 600, 300], ...
           'Color', [0.95, 0.95, 0.95], ...
           'Resize', 'off');
    
    % Create text area with help content
    uicontrol('Parent', hFig, ...
             'Style', 'text', ...
             'String', helpText, ...
             'Position', [20, 60, 560, 220], ...
             'HorizontalAlignment', 'left', ...
             'BackgroundColor', [1, 1, 1], ...
             'ForegroundColor', [0, 0, 0], ...
             'FontSize', 10);
    
    % Add close button
    uicontrol('Parent', hFig, ...
             'Style', 'pushbutton', ...
             'String', 'Close', ...
             'Position', [175, 20, 100, 30], ...
             'Callback', @(~,~) close(hFig));
end